services:
  - name: whiteboard-frontend
    type: static
    repo: https://github.com/motivated-star/Whiteboard-App/tree/main/frontEnd
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_SERVER_URL
        value: "https://whiteboard-app-thd8.onrender.com"
